#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

quote="$(/usr/games/fortune -s linux linuxcookie computers | fold -sw "${WIDTH}")"

print_columns "Fortune" "${quote}"
